### ISSUE TITLE
The uninstall button does not work (raises an exception)

### ISSUE THREAD

**Issue by ghost** [matthew-andrews/serviceworker-simple#2]
When trying to install the service worker the following exception is raised:

`Uncaught TypeError: navigator.serviceWorker.unregister is not a function`

because the unregister function has to be called on a ServiceWorkerRegistration object.

See the JS Fiddle below:

https://jsfiddle.net/franciov/q1hjer8c/2/

**Comment by matthew-andrews** [comment]
Can't keep up with the service worker spec at times :)

**Comment by ghost** [comment]
@matthew-andrews Hehe, yea, no worries. This example helped testing the SW integration in JSFiddle.
